version: 2
updates:
- package-ecosystem: nuget
  directory: "/analytics"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/bookmarklet"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
